config/routes.rb
Rails.application.routes.draw do
  # 
  resources :fields do 
    resources :reviews
  end

  resources :users
  
  root 'fields#index'

  # get 'fields/' => "fields#index"
  # get 'fields/new' => "fields#new", as: :new_field
  # post 'fields/' => "fields#create"
  # get 'fields/:id' => "fields#show", as: :field
  # get 'fields/:id/edit' => "fields#edit", as: :edit_field
  # patch 'fields/:id' => "fields#update"
  # delete 'fields/:id' => "fields#destroy"


  # get "users" => "users#index"
  # get "users/new" => "users#new"
  # post "users" => "users#create"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

#  fields GET    /fields(.:format)          fields#index
#            POST   /fields(.:format)          fields#create
#  new_field GET    /fields/new(.:format)      fields#new
# edit_field GET    /fields/:id/edit(.:format) fields#edit
#      field GET    /fields/:id(.:format)      fields#show
#            PATCH  /fields/:id(.:format)      fields#update
#            PUT    /fields/:id(.:format)      fields#update
#            DELETE /fields/:id(.:format)      fields#destroy



  # get 'users/index'

  # get 'users/show'

  # get 'users/new'

  # get 'users/create'

  # get 'users/edit'

  # get 'users/update'

  # get 'users/destroy'

  # get 'reviews/index'

  # get 'reviews/show'

  # get 'reviews/new'

  # get 'reviews/create'

  # get 'reviews/edit'

  # get 'reviews/update'

  # get 'reviews/destroy'


  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

 
end

app/models/field.rb
class Field < ActiveRecord::Base
	has_many :reviews
	has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :field
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :fields, through: :reviews
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  	include SessionsHelper

  	def authorized?
  		redirect_to root_path unless current_user
  	end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def index
    @fields = Field.all
  end

  def show
    @fields = Field.find(params[:id])
  end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new(field_params)
    if @field.save
      redirect_to fields_path
    else
      render :new
    end
  end

  def edit
    @field = Field.find(params[:id])
  end

  def update
    @field = Field.find(params[:id])
    if @field.update_attributes(field_params)
        redirect_to fields_path
    else
      render :edit
    end
  end

  def destroy
    @field = Field.find(params[:id])
    @field.destroy
      redirect_to fields_path
  end
end

private 
    def field_params
      params.require(:field).permit(:name, :team, :league, :address)
    end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authorized?, except: :index

	def index
		@field = get_field
		@review = Review.find.all
	end

	def show
		@field = get_field
		@review = get_review
	end

	def new
		@field = get_field
		@review = @field.reviews.build
	end

	def edit
		@review = get_review
		redirect_to fields_path(Field.find(params[:field_id])) unless @review.user == current_user
	end

	def update
		@field = get_field
		@review = get_review
		review = Review.find(params[:id])
		if review.user == current_user
			review.update_attributes(review_params)
			@review = get_review
		else
			redirect_to edit_field_review_path 
		end
	end

	def create
		@field = get_field
		@review = @field.reviews.new(review_params)
		@review.user = current_user
		@review.save
		redirect_to fields_path
	end

	def destroy
		@field = get_field
		@review = get_review
		@review.destroy
		redirect_to fields_path
	end

	private 
	def review_params
		params.require(:review).permit(:comments, :rating)
	end

	def get_field
		Field.find(params[:field_id])
	end

	def get_review
		get_field.reviews.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:login][:email])
		if user && user.authenticate(params[:login][:password])
		session[:user_id] = user.id.to_s
		redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fields/edit.html.erb
<h2>Edit a Field </h2>

<%= form_for @field do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :team %>
		<%= f.text_field :team %>
	</div>

	<div>
		<%= f.label :league %>
		<%= f.text_field :league %>
	</div>

	<div>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>

	<%= f.submit "Update Field!" %>

<% end %>
<button class="btn btn-default" type="submit">
<%= link_to "Back to list", fields_path %> </button>

app/views/fields/index.html.erb
<div class="main">
  <h1>Fields of Dreams </h1>

  	<!-- <button class="btn btn-default" type="submit">
  	<%#=link_to "Create Field", new_field_path %></button> -->
  <nav>	
  
  	<% @fields.each do |s| %>
  		<li>
  		<%= s.name %>
  		<button class="btn btn-default btn-sm" type="submit">
  		<%= link_to "Visit Stadium", field_path(s) %></button>
  		</li>
  	<% end %>
  </nav>
</div>
  

app/views/fields/new.html.erb
<h2>Add a New Field </h2>

<%= form_for @field do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :team %>
		<%= f.text_field :team %>
	</div>

	<div>
		<%= f.label :league %>
		<%= f.text_field :league %>
	</div>

	<div>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>

	<%= f.submit "Add a new Field!" %>

<% end %>

<button class="btn btn-default" type="submit">
<%= link_to "Back to list", fields_path %></button>

app/views/fields/show.html.erb
<div class ="container" id="paul">

<h1> <%= @fields.name %> </h1> 


	<p> This field is the home of the <%= @fields.team %>, it is in the <%= @fields.league %>, it is located at <%= @fields.address %>
	</p>

<% @fields.reviews.each do |f| %>
	<%= f.comments %> Rating: <%= f.rating %> - posted by <strong> <%= f.user.name %> </strong>
	<% if f.user == current_user %> 
	<br>
		<button class="btn btn-default" type="submit">
		<%= link_to 'edit', edit_field_review_path(@fields, f) %> </button>
		<button class="btn btn-default" type="submit">
		<%= link_to 'delete', field_review_path(@fields, f), method: :delete %> </button>
	<% end %>
	<br>
<% end %>

<br>

<button class="btn btn-default" type="submit">
<%= link_to 'Back to Stadium List', fields_path %> </button>

<button class="btn btn-default" type="submit">
<%= link_to 'Review Stadium', new_field_review_path(@fields) %> </button>

<!-- <button class="btn btn-default" type="submit">
<%#= link_to "Update Field", edit_field_path %> </button> -->

<!-- <button class="btn btn-default" type="submit">
<%#= link_to "Delete Field", field_path, method: :delete, data: {confirm: "Are you sure you want to delete this field"} %> </button> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<button class="btn btn-default" type="submit">
<%= link_to "Home", root_path %></button>
<% if current_user %>
  Logged in as: <%= current_user.name %> 
  <button class="btn btn-default" type="submit"><%= link_to 'Log Out', logout_path, method: :delete %></button>
<% else %>
  <button class="btn btn-default" type="submit">
  <%= link_to 'Log In', login_path %></button>
  
  <button class="btn btn-default" type="submit">
  <%= link_to 'Sign Up', new_user_path %></button>
<% end %>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@review.field, @review] do |f| %>

	<div class="field">
		<%= f.label :comments %> <br>
		<%= f.text_area :comments, size: "40x6" %>
	</div>

	<div class="rating">
		<%= f.label :rating %> <br>
		<%= f.text_field :rating %>
	</div>
	<br>
	<div class="actions">
			<%= f.submit %>
	</div>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Your Review </h1>

	<%= form_for [@review.field, @review] do |f| %>

	<div class="field">
		<%= f.label :comments %> <br>
		<%= f.text_area :comments, size: "40x6" %>
	</div>

	<div class="rating">
		<%= f.label :rating %> <br>
		<%= f.text_field :rating %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>
<br>
<button class="btn btn-default" type="submit">
<%= link_to "Back to Stadiums List", fields_path %> </button>

app/views/reviews/index.html.erb
<h1> Review for <% @field.name %> has been deleted! </h1>

	<div class="field">
		<%= label :comments %> <br>
		<%= text_area :comment, size: "40x6" %>
	</div>

	<div class="rating">
		<%= label :rating %> <br>
		<%= text_area :rating %>
	</div>

	<% end %>
	<br>
<button class="btn btn-default" type="submit">
<%= link_to 'Back to Stadiums List!', fields_path %> </button>

app/views/reviews/new.html.erb
<h1> Add a Review for <%= @field.name %> </h1>

<%= render "form" %>

<br>
<button class="btn btn-default" type="submit">
<%= link_to 'Back to Stadium List', fields_path %> </button>

app/views/reviews/update.html.erb
<%= form_for [@review.field, @review] do |f| %>

	<div class="field">
		<%= f.label :comments %> <br>
		<%= f.text_area :comments, size: "40x6" %>
	</div>

	<div class="rating">
		<%= f.label :rating %> <br>
		<%= f.text_field :rating %>
	</div>
<% end %>

<br>
<button class="btn btn-default" type="submit">
<%= link_to 'Back to Stadiums List', fields_path %> </button>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
	<% @users.each do |user| %>
	<li><%= user.name %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.text_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation %>
		<%= f.text_field :password_confirmation %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>